apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nginx

resources:
- ../../base

replicas:
- name: nginx-deployment
  count: 2

configMapGenerator:
- envs:
  - .env
  name: nginx-envs
